### ISSUE TITLE
1.19 WITHOUT building the gradle

### ISSUE THREAD

**Issue by DiscoDude96** [MrScautHD/Beyond-Earth#156] opened 2022-08-20 01:41 UTC
### Describe the feature

I do not understand why the fuck this has to be so complicated, I am literally breaking into tears, it's time somebody does something about this. You do know there are uneducated beings on this platform that play 1.19 that actually have zero fucking clue on how to do this. I've asked nicely multiple times, but this has crossed the line for me.
Also my little bro got mad at this and smashed the keyboard so this is the new one, thanks alot.
I still don't know if this is actually being worked on, but if it's not, please just add the pre installed .jar file so I (ahem...) we don't lose the shit.

**Comment by SussyAmgogus** [comment] 2022-08-20 16:14
Hey! :(
This is a duplicate of MY template!

**Comment by MrScautHD** [comment] 2022-08-21 15:42
Pls, if you not know to build projects then just wait on the release version :)

**Closed as completed by MrScautHD** 2022-08-21 15:42 UTC

**Comment by SussyAmgogus** [comment] 2022-08-22 23:09
Yeah ikr like my guy needs to CHILL

**Comment by MrScautHD** [comment] 2022-08-23 09:53
or check the dc for dev versions

**Comment by SussyAmgogus** [comment] 2022-08-24 21:54
what's that? I'm new sorry
